### PR TITLE
Add __version__ munging to the package uploaded to PyPI.

### LINKED ISSUE #127: The release action is publishing .py with invalid __version__
@lesamouraipourpre originally reported this in the Build Tools repo: https://github.com/adafruit/circuitpython-build-tools/issues/70

And they gave an EXCELLENT assessment of the issue

> After reading far too much documentation and github repos I think I've got it figured down as follows:
> 
> Currently in `.github/workflows/release.yml` (simplified):
> 
> - build the release bundles (.py, & .mpy) for github and used by `circup`. As part of this `circuitpython-build-tools` munges the version information into the files with the method `_munge_to_temp`
> - `python setup.py sdist` and `python setup.py bdist_wheel --universal`. These are what gets uploaded to PyPi and are using the unmunged files.
> 
> The fix would be to move the version munging to it's own earlier step and do it in place. The files are going to be deleted from the (docker?) container anyway once the release is completed:
> 
> - munge the version information into the files in place.
> - build the release bundles for github.
> - `python setup.py` for uploading to PyPi.
> 
> This is far above the knowledge level that I feel I have in relation to github/PyPi/CircuitPython and I don't know if this is a viable way to achieve this.

### PR DESCRIPTION
**Pull request by lesamouraipourpre**
Fixes #127 - The version uploaded to PyPI has `__version__ == 0.0.0-auto.0`

This PR builds the PyPI distributable but before uploading with `twine` it

- extracts the package
- uses `sed` to replace `0.0.0-auto.0` with `${{github.event.release.tag_name}}`
- repackages the package

This has been test on 
https://github.com/lesamouraipourpre/Community_CircuitPython_TCA9555/releases/tag/0.0.1-beta.2
as uploaded to:
https://pypi.org/project/community-circuitpython-tca9555/0.0.1b2/#files

### CODE REVIEW

**Review by jepler — APPROVED** [review]
I did not test this, but it looks OK (I sort-of tested that the `{{github...}}` blocks were _NOT_ substituted by cookiecutter, though I don't know why not) and in reading about distutils/setuputils I didn't see a different and more "canonical" way of doing this proposed.

**Comment by kattni** [comment]
@lesamouraipourpre Is this ready to be merged? I'm looking to move the repo from `master` to `main` and while it's pretty simple to move PRs, it would be easier not to.

**Comment by lesamouraipourpre** [comment]
> 
> 
> @lesamouraipourpre Is this ready to be merged? I'm looking to move the repo from `master` to `main` and while it's pretty simple to move PRs, it would be easier not to.
Yes, it's ready.

**Comment by kattni** [comment]
@lesamouraipourpre I merged the other PR and now there are merge conflicts. Can you please get those resolved? I will merge the PR when it's ready. Thanks!

**Pull request merged**
