### PR TITLE
Fix typos and add setup.py.disabled if user chooses no for PyPI release

### PR DESCRIPTION
**Pull request by makermelissa**

### CODE REVIEW

**Comment by askpatrickw** [comment]
@makermelissa  I wanted to double check one thing.
If the user is not going to release to PyPi you still want setup.py to created as setup.disabled instead of not created at all?

**Comment by askpatrickw** [comment]
There are other things not included things when you select PyPi no.

Is the goal to have PyPi just be disabled so you can enable it later? Maybe if you say pypi yes it should just be setup.disabled and then you can do dev work but enable it by renaming setup.disabled to setup.py.

The PyPi could be a choice (Enable, Disable, None) instead of a Yes\No... 

If this is exactly what is wanted cool. Just wanted to mention those things.

**Comment by dhalbert** [comment]
@makermelissa Do you want to consider @askpatrickw's suggestions before merging, or just add this for now?

**Comment by makermelissa** [comment]
Ah, I seemed to have missed @askpatrickw 's comments. I would like it the way it is.

**Comment by askpatrickw** [comment]
I think there is a future where there is a Community version of this and an Adafruit version of this so I say merge away and it will get sorted later. ;-)

**Review by askpatrickw — APPROVED** [review]

**Review by dhalbert — COMMENTED** [review]
:+1:

**Pull request merged**
