### PR TITLE
Check formatting via black

### PR DESCRIPTION
**Pull request by jreese**
adafruit/circuitpython#2608

### CODE REVIEW

**Comment by siddacious** [comment]
@jreese ooh sweet! I started using black locally and overall I like it a lot. I did run into one issue where pylint didn't like its output, but we may be able to surmount that.

I'll try and quickly put together a test case but if I recall correctly it was a disagreement about indent depth when continuing a long line on the next line

**Comment by jreese** [comment]
Yeah, it's likely that we'll need to disable one or more of the style lints from pylint. I have a fair number of rules disabled for my own projects: https://github.com/jreese/aioitertools/blob/master/.pylint#L57

**Comment by siddacious** [comment]
@jreese can you make a PR against 
https://github.com/adafruit/Adafruit_CircuitPython_TestRepo
with your changes so we can see what a run looks like? You're right to make the actual changes here, however actions doesn't run normally here because it's not a normal repo

**Comment by siddacious** [comment]
@jreese here is a test case:
```
class PuffDetector:
    def __init__(
        self,
        display,
        min_pressure=1,
        high_pressure=2,
        config_filename="settings.json",
        display_timeout=1,
    ):
        self.display = display
        self.state_display_start = 0
        self.detection_result_str = ""
        self.duration_str = ""
        self.high_pressure = high_pressure
        self.min_pressure = min_pressure
        self.display_timeout = display_timeout
        self.config_filename = config_filename
```

**Comment by siddacious** [comment]
locally I get this with the above:
image

**Comment by jreese** [comment]
I think adafruit/actions-ci-circuitpython-libs#5 will need to be accepted before Github Actions will actually be able to run this PR.

**Comment by siddacious** [comment]
@jreese it looks like it's been merged. Wanna give it a go?

**Comment by tannewt** [comment]
@siddacious what needs to be rerun?

**Comment by siddacious** [comment]
@jreese @tannewt my mistake, I missed that you'd already tested this with a PR against TestRepo. Looks good to me, merge away!

**Comment by siddacious** [comment]
Thank you @jreese. 

@tannewt @sommersoft @kattni @dherrada 
I expect and hope that we'll keep making tweaks like this; We should probably discuss formalizing how we want to apply cookiecutter changes to the existing repos.

I'll add this to in the weeds for next Tuesday. I think this change can wait to be applied more broadly until we've had that discussion

**Comment by tannewt** [comment]
Sounds good @siddacious

**Comment by sommersoft** [comment]
@siddacious I was having the same thoughts about ironing out an implementation strategy. I'll double check my schedule for Tuesday; if I can't voice, I'll at least gather some thoughts for the notes.

**Pull request merged**
