### PR TITLE
Fix building MPY bundle for community packages

### PR DESCRIPTION
**Pull request by tekktrik**
Fixes #185 where the workflow YAML files don't account for community packages with or without prefixes because it looked only for folders beginning with `adafruit_`.  This required disabling the `pre-commit` check for YAML files because they aren't valid YAML format anymore.

### CODE REVIEW

**Comment by tekktrik** [comment]
Looked like the tests were faulty:

- Overwriting the extensions doesn't seem necessary, and it was trying to use the list of extensions to see if it was in that list, which is obviously not true, so I removed it
- Seems like there was an `if` that should have been an `elif`, as it kept overwriting the values that were being stored with `"test"`

**Comment by tekktrik** [comment]
@kattni would you mind taking a look at this whenever you get a chance?  Also, I tested it to make sure it solves the issue, but let me know if there's any specific tests you'd like me to do to confirm this change works or doesn't break anything else.

**Comment by tekktrik** [comment]
@kattni did you ever get a chance to look at this? Should fix the weird issue with packages made for the community bundle.  Happy to elaborate on anything!

**Review by kattni — APPROVED** [review]
Looks good to me! Did not test. Merge when ready!

**Pull request merged**
