### PR TITLE
Updates For New Docs Setup

### PR DESCRIPTION
**Pull request by sommersoft**
* Updated `docs/conf.py` `master_doc=` to 'index' (listed in adafruit/circuitpython issue #566)
* Added a title to `docs/api.rst`. Travis/Sphinx complained and wouldn't build.

### CODE REVIEW

**Comment by tannewt** [comment]
The title complaining usually happens when it can't open the module its trying to auto document. Could you link me to the Travis runs you did? Thanks for fixing this up! Sorry it wasn't quite right. I was trying to port it back from the example I did.

**Comment by sommersoft** [comment]
https://travis-ci.org/sommersoft/Adafruit_CircuitPython_Trellis/builds/336753415

**Comment by sommersoft** [comment]
and no worries. lord knows my code goes through plenty of iterations! just look at all the commits I do.

**Comment by tannewt** [comment]
Thanks for the link! Looks like you have your api.rst set to the package (aka folder) name instead of having two entries, one for each module (aka file). Try:
```
.. automodule:: adafruit_trellis.trellis
   :members:

.. automodule:: adafruit_trellis.trellis_set
   :members:
```
and remove the title here.

**Comment by sommersoft** [comment]
I originally was going to go that route. Well, I was going to try `../adafruit_trellis`. But, compared to index/examples.rst I went with the title. I'll change, test, and recommit later tonight. It's movie night!

**Comment by sommersoft** [comment]
Changed to your suggestion. Now receiving this:
```
/home/travis/build/sommersoft/Adafruit_CircuitPython_Trellis/docs/api.rst:4:autodoc: failed to import module 'adafruit_trellis.trellis'; the following exception was raised:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "/home/travis/build/sommersoft/Adafruit_CircuitPython_Trellis/adafruit_trellis/trellis.py", line 49, in <module>
    from micropython import const
ModuleNotFoundError: No module named 'micropython'
```

https://travis-ci.org/sommersoft/Adafruit_CircuitPython_Trellis/builds/336826169

**Comment by tannewt** [comment]
You'll need to add micropython to the automock line in conf.py. This is
good, the docs must not have been building before.

**Comment by sommersoft** [comment]
Ok, its processing now. I've gotten through my docstring snafoos. Now I'm at another Sphinx build issue (I think). I get this warning: 
```
/home/travis/build/sommersoft/Adafruit_CircuitPython_Trellis/docs/api.rst:4:
  'any' reference target not found: adafruit_trellis
``` 
https://travis-ci.org/sommersoft/Adafruit_CircuitPython_Trellis/builds/336955903

The only reference I can find to `any` is in the `conf.py` starting at line 59:
```
# The reST default role (used for this markup: `text`) to use for all
# documents.
#
default_role = "any"
```

After digging through the Sphinx documentation, I can't find that `any` is a defined role. I'm assuming it's setup on the backend? Or do we need to add `.. default-role::` to the lib files?

With regards to the `autodoc_mock_imports`, is it possible to add a prompt during cookiecutter, or a TODO so that it's a little clearer that it may need to be updated? I concede that the comments, **when read**, spell out that it needs to be updated. That one was on me.

I'll roll back the api title commit, and add documentation that gives an example for nested files (e.g. `/adafruit_foo/foo.py`)

**Comment by tannewt** [comment]
Thank you for your perseverance @sommersoft. Feel free to add a todo for the automock imports where you think its appropriate. I'll merge this now since it looks good.

Sounds like you figured out the any reference thing too. Its a stand in for all types of references. If a reference is missing its possible you want a different contents instead. In your example, you want `adafruit_trellis.trellis` instead of `adafruit_trellis` because the package doesn't have any documentation.

**Comment by tannewt** [comment]
Wrong button!

**Pull request merged**
