### PR TITLE
More conf.py Cleanup

### PR DESCRIPTION
**Pull request by sommersoft**
See Issue #20.

### CODE REVIEW

**Comment by tannewt** [comment]
Please add the top-level one back.

**Comment by sommersoft** [comment]
Sorry about that. I assumed based off the information in the `conf` it was a straggler. I'll get it back in this afternoon.

Does it need to have the `MCP9808` info filled in? That was what was throwing me...

**Comment by tannewt** [comment]
Nope, it should be to document the cookiecutter template itself. I
understand why it was confusing. :-)
~Scott

**Comment by sommersoft** [comment]
> Nope, it should be to document the cookiecutter template itself.

I'm still a little confused (what's new?). 

Should cookiecutter have it's own documentation page on RTD, that is config'd by the top level `conf.py`? I haven't seen one, if it exists.

I'm putting the original back now. If you want me to setup RTD/Travis for cookie, I'm willing to tackle it.

**Comment by tannewt** [comment]
Yup, the top-level one is for the cookiecutter's RTD documentation. (I think your right that it isn't set up though.)

**Pull request merged**
