### PR TITLE
Add PR template.

### LINKED ISSUE #134: Suggested library PR template content
Here is my suggestion for the library PR template. This would appear in all PRs opened on any CircuitPython library. Including it here for discussion. We will be deploying this in the next 24-48 hours, so any suggestions must be made ASAP.

Note that this code snippet does not auto-wrap the text, but the PR template will.

```
Thank you for contributing! Before you submit a pull request, please read the following.

Make sure any changes you're submitting are in line with the CircuitPython Design Guide, available here:
https://circuitpython.readthedocs.io/en/latest/docs/design_guide.html

If your changes are to documentation, please verify that the documentation builds locally by following the steps found here: https://adafru.it/build-docs

Before submitting the pull request, make sure you've run Pylint and Black locally on your code. You can do
this manually or using pre-commit. Instructions are available here: https://adafru.it/check-your-code

Please remove all of this text before submitting. Include an explanation or list of changes included in your PR, as well as, if applicable, a link to any related issues.
```

### PR DESCRIPTION
**Pull request by kattni**
Fixes #134. 

Named `adafruit_circuitpython_pr` to allow for a separate community library template in the future if desired.

### CODE REVIEW

**Review by tannewt — APPROVED** [review]
Looks good to me! Thank you!

**Comment by askpatrickw** [comment]
That design guide is really nice !

**Comment by jposada202020** [comment]
This will help new folks, and reviewers

**Comment by kattni** [comment]
Merging as it appears that folks are happy with it.

**Pull request merged**
