### PR TITLE
Update .readthedocs.yml

### PR DESCRIPTION
**Pull request by kattni**

### CODE REVIEW

**Comment by kattni** [comment]
This is not the right fix. Testing the appropriate fix now.

**Comment by kattni** [comment]
Test on MagTag library. Docs were failing remotely on Read the Docs (API section was missing entirely) - updated `.readthedocs.yml` to this `.readthedocs.yaml`, and the docs successfully built remotely.

**Comment by KeithTheEE** [comment]
Looks good. I'm not experienced with sphinx/readthedocs build process though so I could be missing something.

One question before hand, does the base-level requirements.txt need any extra information or can it be left untouched?

**Review by tannewt — APPROVED** [review]

**Comment by kattni** [comment]
@KeithTheEE Untouched. It will be generated for each library as usual, and RTD will use whatever is in it.

**Pull request merged**
