### PR TITLE
update to the latest adafruit community code of conduct

### PR DESCRIPTION
**Pull request by imnotjames**
updates the code of conduct to match the latest revision in `adafruit/Adafruit_Community_Code_of_Conduct`

### CODE REVIEW

**Comment by imnotjames** [comment]
Based on the comments in #230 it should be good to update this document to match.

I'm not sure how the existing repositories could be best updated to match this change.

**Comment by imnotjames** [comment]
Weird!  The 3.x cookiecutter failed because of the pkg_resources bit?  Seems like a separate issue.

**Comment by dhalbert** [comment]
> Weird! The 3.x cookiecutter failed because of the pkg_resources bit? Seems like a separate issue.

The default version of Python on GitHub CI was updated to 3.12 a few days ago. This is breaking a bunch of things because `setuptools` is no longer provided by default. I am not sure what the point of that change was. We need to investigate that, and whether we should change something about how our CI jobs run.

Tagging @FoamyGuy for interest.

**Comment by imnotjames** [comment]
I'm also realizing that I might be misunderstanding where the various code of conducts should be pulled from - the differences between the community code of conduct & the standard adafruit one.

**Comment by imnotjames** [comment]
PS I tried to match the circuitpython changes to the adafruit changes - using circuitpython where appropriate and dropping references to the adafruit discord.  If there's a more official source for the circuitpython code of conduct I'll happily get that in place. :)

**Comment by imnotjames** [comment]
I'm going to renew this so the tests (hopefully) pass

**Review by FoamyGuy — APPROVED** [review]
This looks good to me. Thank you @imnotjames!

**Pull request merged**
