### PR TITLE
Change `pid` prompt to `product_id`

### LINKED ISSUE #152: adafruit_pid prompt is confusing
When I run cookiecutter with this package it asks me for `adafruit_pid`. This is where you put the Adafruit product id. You get a link to the product page in your package documentation.

I think it would be clearer if the prompt were `adafruit_product_id`.

### PR DESCRIPTION
**Pull request by ajs256**
Close #152 by switching the `adafruit_pid` prompt to `adafruit_product_id`.

P.S. to maintainers: could you please label this pull request with `hacktoberfest-accepted` after you merge it so it counts for Hacktoberfest? Thanks!

### CODE REVIEW

**Review by jepler — APPROVED** [review]
Thank you!

**Comment by ajs256** [comment]
Hi @jepler, if this repo is participating in Hacktoberfest, could you please add the `hacktoberfest-accepted` label to this PR? Thanks!

**Comment by askpatrickw** [comment]
I added the hacktoberfest tag. Thanks @ajs256

**Comment by ajs256** [comment]
@askpatrickw it needs to be `hacktoberfest-accepted` to count

**Comment by askpatrickw** [comment]
I'm letting the team know.

**Pull request merged**
