### PR TITLE
ci(pre-commit): bump pre-commit hooks

### PR DESCRIPTION
**Pull request by xsc27**

### CODE REVIEW

**Comment by askpatrickw** [comment]
@kattni  Did you want to bump these versions?

**Comment by kattni** [comment]
@xsc27 Thanks for the submission! Do you have any idea what changes between the currently pinned version of pre-commit-hooks and the latest version?

Unfortunately, updating Pylint means fixing all of the libraries to work with the latest version of Pylint, which we do not currently have the cycles for. Basically if we update pre-commit pins here, we need to update them across the libraries as well for consistency. Therefore, Pylint should not be updated.

As long as the reuse-tool and pre-commit-hooks updates will not break things in the libraries, I'm happy to update those.

**Comment by xsc27** [comment]
hmm. `pylint` will probably need an update to the rcfile to disable any new checks, at a minimum.

The `reuse-tool` adds support for more files.

`pre-commit-hooks` adds new hooks (which are not added to the cookie-cutter). Other additions include:
- improved output
- more flags for hooks
- maintenance

**Comment by xsc27** [comment]
@kattni new push w/o bumping `pylint`

**Review by kattni — APPROVED** [review]
Thanks for the updates! Making a note to put together a patch for the libraries!

**Pull request merged**
