### PR TITLE
Always generate PyPI infrastructure

### LINKED ISSUE #191: Always publish packages to PyPI
In order to better work with Thonny, all packages going forward will be published to PyPI even if they do not work with standard/desktop Python.  Remove the questions about this and make it unconditional.

### PR DESCRIPTION
**Pull request by tekktrik**
Per @jepler's and @evaherrada's work to ensure all packages are available on PyPI for Mu, this PR updates the cookiecutter so that this infrastructure is always generated and is no longer one of the configurable options.

Resolves #191

### CODE REVIEW

**Review by askpatrickw — COMMENTED** [review]
I don't see this in the Issue or the comments, maybe it was discussed elsewhere. What happens for community libraries? What else do they need to do to set that up?

**Comment by tekktrik** [comment]
Community libraries need to set up things in the repository like secrets, but there's no downside for community libraries for providing the infrastructure, even if they don't use it.

**Comment by askpatrickw** [comment]
Since the GH Action is part of the template, it would be good to document that in the README.rst.

https://github.com/adafruit/cookiecutter-adafruit-circuitpython/blob/main/%7B%7B%20cookiecutter.__dirname%20%7D%7D/.github/workflows/release.yml#L60

```yaml
- name: Build and publish
      if: contains(steps.need-pypi.outputs.pyproject-toml, 'pyproject.toml')
      env:
        TWINE_USERNAME: {% raw %}${{ secrets.pypi_username }}{% endraw %}
        TWINE_PASSWORD: {% raw %}${{ secrets.pypi_password }}{% endraw %}
```

**Comment by tekktrik** [comment]
Added instruction to cookiecutter repo README for adding secrets

**Review by kattni — APPROVED** [review]
Looks good to me. Did not test it. @tekktrik Looks like pre-commit is failing. Feel free to merge once the PR is passing, unless you make major changes in the meantime, in which case, mark it ready for  re-review. Thanks!

**Comment by tekktrik** [comment]
Rebased this, to get access to the formatting but otherwise the same

**Pull request merged**
